# Generated by Django 5.0.6 on 2024-07-03 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('dataDeNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('dataDeMorte', models.DateField(blank=True, null=True, verbose_name='Data de Morte')),
            ],
            options={
                'ordering': ['sobrenome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o genero do livro (Ex: Ficção Científica)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myFieldName', models.CharField(help_text='Primeiro Nome', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text='Digite o título do livro', max_length=200, verbose_name='Titulo')),
                ('resumo', models.TextField(help_text='Digite o resumo do livro', max_length=1000, verbose_name='Resumo')),
                ('isbn', models.CharField(help_text='Número ISBN do livro', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(help_text='Digite o autor do livro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.autor')),
                ('genero', models.ManyToManyField(help_text='Digite o gênero do livro', to='catalog.genre')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dataDeDevolucao', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Em manutenção'), ('e', 'Emprestado'), ('d', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do livro', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book')),
            ],
            options={
                'ordering': ['-dataDeDevolucao'],
            },
        ),
    ]
