# Generated by Django 5.0.6 on 2024-07-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genero',
        ),
        migrations.AlterModelOptions(
            name='mymodelname',
            options={'ordering': ['-myFieldName']},
        ),
    ]
