# Generated by Django 5.0.6 on 2024-07-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_genre_genero_alter_mymodelname_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='name',
            new_name='nome',
        ),
    ]
