# Generated by Django 5.0.6 on 2024-07-08 12:14

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_name_genero_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', length=5, max_length=8, prefix='id_', primary_key=True, serialize=False),
        ),
    ]
