# Generated by Django 5.0.6 on 2024-07-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_imprint_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['dataDeDevolucao']},
        ),
        migrations.AlterModelOptions(
            name='mymodelname',
            options={'ordering': ['myFieldName']},
        ),
    ]
